"""initial schema

Revision ID: 3908a5afd525
Revises: 
Create Date: 2026-09-16 12:09:24.666106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3908a5afd525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    op.create_table('trips',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('home_base_note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('share_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_share_slug'), ['share_slug'], unique=True)

    op.create_table('places',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('precision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_maps_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_places_trip_id'), ['trip_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_subject_kind'), ['subject_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_members',
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('trip_id', 'user_id')
    )
    op.create_table('days',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['base_place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_days_trip_id'), ['trip_id'], unique=False)

    op.create_table('lodgings',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('booking_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lodgings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lodgings_trip_id'), ['trip_id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('booking_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_day_id'), ['day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_trip_id'), ['trip_id'], unique=False)

    op.create_table('gaps',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_by_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resolved_by_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gaps_day_id'), ['day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gaps_trip_id'), ['trip_id'], unique=False)

    op.create_table('transits',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('from_place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('to_place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('depart_at', sa.DateTime(), nullable=True),
    sa.Column('arrive_at', sa.DateTime(), nullable=True),
    sa.Column('booking_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ),
    sa.ForeignKeyConstraint(['from_place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['to_place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transits_day_id'), ['day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transits_trip_id'), ['trip_id'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gap_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('place_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pros', sa.JSON(), nullable=True),
    sa.Column('cons', sa.JSON(), nullable=True),
    sa.Column('confidence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['gaps.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_gap_id'), ['gap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_trip_id'), ['trip_id'], unique=False)

    op.create_table('research_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gap_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nudge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['gaps.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_jobs_gap_id'), ['gap_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_jobs_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_jobs_trip_id'))
        batch_op.drop_index(batch_op.f('ix_research_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_research_jobs_gap_id'))

    op.drop_table('research_jobs')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_trip_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_gap_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('transits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transits_trip_id'))
        batch_op.drop_index(batch_op.f('ix_transits_day_id'))

    op.drop_table('transits')
    with op.batch_alter_table('gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gaps_trip_id'))
        batch_op.drop_index(batch_op.f('ix_gaps_day_id'))

    op.drop_table('gaps')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_trip_id'))
        batch_op.drop_index(batch_op.f('ix_activities_day_id'))

    op.drop_table('activities')
    with op.batch_alter_table('lodgings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lodgings_trip_id'))

    op.drop_table('lodgings')
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_days_trip_id'))

    op.drop_table('days')
    op.drop_table('trip_members')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_trip_id'))
        batch_op.drop_index(batch_op.f('ix_sources_subject_kind'))
        batch_op.drop_index(batch_op.f('ix_sources_subject_id'))

    op.drop_table('sources')
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_places_trip_id'))

    op.drop_table('places')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_share_slug'))
        batch_op.drop_index(batch_op.f('ix_trips_owner_id'))

    op.drop_table('trips')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
