"""trip invites

Revision ID: 4061bdf2d054
Revises: 9be2daf15664
Create Date: 2026-09-16 19:26:41.728534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4061bdf2d054'
down_revision: Union[str, Sequence[str], None] = '9be2daf15664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_invites',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_invites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_invites_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_invites_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_invites_email'))

    op.drop_table('trip_invites')
    # ### end Alembic commands ###
