"""geocoding and trip destinations

Revision ID: 640842779c30
Revises: a3c098d2083c
Create Date: 2026-09-16 13:06:29.201602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '640842779c30'
down_revision: Union[str, Sequence[str], None] = 'a3c098d2083c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('query')
    )
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geocoded_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destinations', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('destinations')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('geocoded_at')

    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
