"""intake sessions

Revision ID: 7d0ce0ba43cd
Revises: 1ee2153643ab
Create Date: 2026-09-16 19:45:47.054623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7d0ce0ba43cd'
down_revision: Union[str, Sequence[str], None] = '1ee2153643ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('current_draft', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intake_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intake_sessions_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intake_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intake_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intake_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_intake_sessions_trip_id'))

    op.drop_table('intake_sessions')
    # ### end Alembic commands ###
