"""trip travelers and interests

Revision ID: a3c098d2083c
Revises: 3908a5afd525
Create Date: 2026-09-16 12:42:23.945378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a3c098d2083c'
down_revision: Union[str, Sequence[str], None] = '3908a5afd525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travelers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('interests')
        batch_op.drop_column('travelers')

    # ### end Alembic commands ###
