"""agent runs cost ledger

Revision ID: bfa2489e3f9c
Revises: b5dcd8d40d2c
Create Date: 2026-09-23 19:14:23.849529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfa2489e3f9c'
down_revision: Union[str, Sequence[str], None] = 'b5dcd8d40d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trip_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intake_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('research_job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('searches', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_intake_session_id'), ['intake_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # Carry over costs already recorded on research jobs. Only one attempt per
    # job was ever kept, and cache tokens and the model weren't stored.
    op.execute("""
        INSERT INTO agent_runs (id, kind, ok, user_id, trip_id, research_job_id, model,
            input_tokens, output_tokens, cache_write_tokens, cache_read_tokens, searches, cost_usd, created_at)
        SELECT j.id, 'research', j.status = 'done', t.owner_id, j.trip_id, j.id, '',
            j.input_tokens, j.output_tokens, 0, 0, j.search_count, j.cost_usd,
            COALESCE(j.finished_at, j.created_at)
        FROM research_jobs j JOIN trips t ON t.id = j.trip_id
        WHERE j.cost_usd > 0
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_trip_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_kind'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_intake_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_created_at'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
