"""geocode cache categories; reset city pins

Revision ID: ec17ce26a9a0
Revises: 640842779c30
Create Date: 2026-09-16 16:40:34.058782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec17ce26a9a0'
down_revision: Union[str, Sequence[str], None] = '640842779c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Old cache rows came from free-text "City, Destination" lookups that could
    match shops and streets (Paris -> a shop in Edinburgh). Drop them, and
    reset city pins so every trip is re-located with structured lookups the
    next time its board loads.
    """
    op.execute("DELETE FROM geocode_cache")
    with op.batch_alter_table('geocode_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.execute(
        "UPDATE places SET lat = NULL, lng = NULL, precision = 'unknown', geocoded_at = NULL WHERE kind = 'city'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geocode_cache', schema=None) as batch_op:
        batch_op.drop_column('country_code')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
